services:
  cli:
    image: tcpdf-markdown:latest
    build:
      context: ./
    volumes:
      - ./:/github/workspace
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=php