on: [push]

jobs:
  phpunit-tests:
    runs-on: ubuntu-latest
    name: run phpunit tests
    steps:
      - uses: actions/checkout@v4
      - name: build docker image
        uses: ./.github/actions/default
      - run: composer install
      - name: run phpunit with coverage
        run: XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover clover.xml
      - name: upload coverage to coveralls
        run: vendor/bin/php-coveralls -v
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}